// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4MbXsiy4LCIdUFVQ2FVgviXuiMPUtXyE',
    appId: '1:840672481262:web:29703c8b506b0666a548ff',
    messagingSenderId: '840672481262',
    projectId: 'odontologiaapp-d273f',
    authDomain: 'odontologiaapp-d273f.firebaseapp.com',
    storageBucket: 'odontologiaapp-d273f.firebasestorage.app',
    measurementId: 'G-MXRCNED169',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNomgZjXUkBZPDUpS4ExC-rJRqALYLF1c',
    appId: '1:840672481262:android:238db6c048bc958ea548ff',
    messagingSenderId: '840672481262',
    projectId: 'odontologiaapp-d273f',
    storageBucket: 'odontologiaapp-d273f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYaz9H-DMuotr_7JWuwrA7vGM5HVZQZyU',
    appId: '1:840672481262:ios:2999d0fb3e271eaea548ff',
    messagingSenderId: '840672481262',
    projectId: 'odontologiaapp-d273f',
    storageBucket: 'odontologiaapp-d273f.firebasestorage.app',
    iosBundleId: 'com.example.odontologiaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYaz9H-DMuotr_7JWuwrA7vGM5HVZQZyU',
    appId: '1:840672481262:ios:2999d0fb3e271eaea548ff',
    messagingSenderId: '840672481262',
    projectId: 'odontologiaapp-d273f',
    storageBucket: 'odontologiaapp-d273f.firebasestorage.app',
    iosBundleId: 'com.example.odontologiaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4MbXsiy4LCIdUFVQ2FVgviXuiMPUtXyE',
    appId: '1:840672481262:web:f48c10673285931aa548ff',
    messagingSenderId: '840672481262',
    projectId: 'odontologiaapp-d273f',
    authDomain: 'odontologiaapp-d273f.firebaseapp.com',
    storageBucket: 'odontologiaapp-d273f.firebasestorage.app',
    measurementId: 'G-HHQ7JNKNZ8',
  );

}